# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ('-checkins',)},
        ),
    ]
