# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Search_Restaurant' do
source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'8.1'
pod 'GoogleMaps'
pod 'Alamofire', '~> 3.0'
end

target 'Search_RestaurantTests' do

end

target 'Search_RestaurantUITests' do

end

